version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npx yarn
      - run: npm run build
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build --tag lexland/lex-server:latest .
      - run: docker push lexland/lex-server:latest
  deploy:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 'a6:f7:79:2b:9f:58:f2:db:1e:2e:4d:14:95:29:4c:c3'
      - run:
          name: Copy Files
          command: |
            scp -r docker/** $SSH_USER@$SSH_HOST:/root
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "docker-compose pull && docker-compose down --remove-orphans && docker-compose up -d"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
